'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, MessageCircle, Send, Shield, UserPlus, Users, X } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
import { defaultProfile, type Profile } from '@/lib/model';
import { Toaster, toast } from 'sonner';

type PublicProfile = { publicId: string; displayName: string; hub: string; cohort: 'teen'|'adult'; bio: string; interests: string[]; intent: string; introvert: boolean; discoverable: boolean; updatedAt: number };
type Request = { id: string; direction: 'incoming'|'outgoing'; state: 'pending'|'accepted'|'declined'|'cancelled'; person: PublicProfile; updatedAt: number };
type Message = { id: string; fromMe: boolean; personId?: string; body: string; createdAt: number };
type Snapshot = { me: PublicProfile|null; people: PublicProfile[]; requests: Request[]; contacts: PublicProfile[]; messages: Message[] };
const empty: Snapshot = { me:null, people:[], requests:[], contacts:[], messages:[] };

export default function CommunityClient() {
  const [snapshot,setSnapshot]=useState<Snapshot>(empty);
  const [privateProfile,setPrivateProfile]=useState<Profile>(defaultProfile);
  const [bio,setBio]=useState('');
  const [discoverable,setDiscoverable]=useState(false);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<string>('');
  const [body,setBody]=useState('');
  const activeContact=snapshot.contacts.find((person)=>person.publicId===selected) ?? snapshot.contacts[0];
  const conversation=useMemo(()=>snapshot.messages.filter((message)=>message.personId===activeContact?.publicId),[snapshot.messages,activeContact?.publicId]);
  async function load(){setLoading(true);try{const [community,state]=await Promise.all([fetch('/api/community'),fetch('/api/state')]);if(community.status===401){location.href='/login';return}const c=await community.json() as Snapshot&{error?:string};const s=await state.json() as {profile?:Profile};if(!community.ok)throw new Error(c.error||'Unable to load community.');setSnapshot(c);setPrivateProfile(s.profile||defaultProfile);setBio(c.me?.bio||'');setDiscoverable(c.me?.discoverable||false);}catch(error){toast.error((error as Error).message);}finally{setLoading(false)}}
  useEffect(()=>{const id=setTimeout(()=>void load(),0);return()=>clearTimeout(id)},[]);
  async function act(action:unknown,success:string){if(busy)return false;setBusy(true);try{const response=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const next=await response.json() as Snapshot&{error?:string};if(!response.ok)throw new Error(next.error||'Unable to save.');setSnapshot(next);toast.success(success);return true;}catch(error){toast.error((error as Error).message);return false;}finally{setBusy(false)}}
  async function saveProfile(){await act({kind:'join',profile:{displayName:privateProfile.name,hub:privateProfile.hub,cohort:privateProfile.cohort,bio,interests:privateProfile.interests,intent:privateProfile.intent,introvert:privateProfile.introvert,discoverable}},snapshot.me?'Community profile updated.':'Community profile created.');}
  async function send(event:FormEvent){event.preventDefault();if(!activeContact||!body.trim())return;if(await act({kind:'message',publicId:activeContact.publicId,body},'Message sent.'))setBody('')}
  return <main className="v3-app community-shell"><Toaster theme="light" position="bottom-right"/><header className="community-top"><Link href="/feed"><ArrowLeft size={18}/>Back to Toveli</Link><div><span className="brand-mark">t</span><b>toveli.</b></div><span className="alpha">PRIVATE PILOT</span></header><div className="community-page"><div className="page-heading"><div><p className="eyebrow">REAL COMMUNITY FOUNDATION</p><h1>Connections begin with consent.</h1><p className="intro-copy">Create a discoverable profile, exchange a request, then message after both people agree.</p></div></div>
  <section className="community-profile panel"><div><h2>Your community profile</h2><p>It uses your saved Toveli interests. Your email is never shown.</p></div><label className="field">Short introduction<textarea maxLength={240} value={bio} onChange={(event)=>setBio(event.target.value)} placeholder="What would you enjoy doing with someone from your campus?"/></label><div className="switch-row"><div><b>Appear to compatible pilot members</b><p>Only members in the same selected hub and age group can see this profile.</p></div><Switch checked={discoverable} onCheckedChange={setDiscoverable} aria-label="Appear in community discovery"/></div><button className="primary" disabled={loading||busy} onClick={saveProfile}>{snapshot.me?'Update profile':'Join the pilot'}<ArrowRight size={17}/></button></section>
  {!snapshot.me?<section className="empty tall"><Users size={42}/><h2>Join when your preferences feel right.</h2><p>Set your name, hub, interests, and age group in onboarding first.</p><Link className="outline" href="/onboard">Review onboarding</Link></section>:<>
  <section className="community-section"><div className="section-title"><div><p className="eyebrow">DISCOVER</p><h2>Compatible pilot members</h2></div><span>{snapshot.people.length}</span></div>{snapshot.people.length?<div className="people-grid">{snapshot.people.map((person)=><article className="person" key={person.publicId}><div className="person-top"><span className="avatar blue">{person.displayName.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><span className="tag-label">{person.cohort==='teen'?'TEEN PEER':'ADULT'}</span></div><h3>{person.displayName}</h3><p className="meta">{person.hub} · {person.intent}</p><p className="bio">{person.bio||'Starting with shared interests.'}</p><div className="tags">{person.interests.filter((interest)=>snapshot.me?.interests.includes(interest)).map((interest)=><span key={interest}>{interest}</span>)}</div><button className="primary full" disabled={busy} onClick={()=>act({kind:'request',publicId:person.publicId},'Connection request sent.')}>Request to connect<UserPlus size={17}/></button><button className="text-button" disabled={busy} onClick={()=>act({kind:'block',publicId:person.publicId},'Member hidden.')}>Hide this member</button></article>)}</div>:<div className="empty"><Users size={32}/><h2>No compatible pilot members yet.</h2><p>Your profile is ready. New members will appear only when their hub and age group match yours.</p></div>}</section>
  <section className="community-section"><div className="section-title"><div><p className="eyebrow">REQUESTS</p><h2>Mutual connection</h2></div><span>{snapshot.requests.filter(request=>request.state==='pending').length}</span></div>{snapshot.requests.length?snapshot.requests.map((request)=><article className="request-row" key={request.id}><span className="avatar pink">{request.person.displayName.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><b>{request.person.displayName}</b><p>{request.direction==='incoming'?'Wants to connect with you':'Your request'} · {request.state}</p></div>{request.state==='pending'&&request.direction==='incoming'&&<div className="request-actions"><button className="primary" disabled={busy} onClick={()=>act({kind:'respond',requestId:request.id,accept:true},'Connection accepted.')}><Check size={17}/>Accept</button><button className="outline" disabled={busy} onClick={()=>act({kind:'respond',requestId:request.id,accept:false},'Request declined.')}><X size={17}/>Decline</button></div>}{request.state==='pending'&&request.direction==='outgoing'&&<button className="outline" disabled={busy} onClick={()=>act({kind:'cancel',requestId:request.id},'Request cancelled.')}>Cancel</button>}</article>):<div className="empty">Connection requests will appear here.</div>}</section>
  <section className="community-section"><div className="section-title"><div><p className="eyebrow">MESSAGES</p><h2>Accepted connections</h2></div><span>{snapshot.contacts.length}</span></div>{snapshot.contacts.length?<div className="real-chat"><nav>{snapshot.contacts.map((person)=><button key={person.publicId} className={activeContact?.publicId===person.publicId?'active':''} onClick={()=>setSelected(person.publicId)}><span className="avatar orange">{person.displayName.split(' ').map(part=>part[0]).slice(0,2).join('')}</span>{person.displayName}</button>)}</nav><div className="real-thread"><header><MessageCircle size={19}/><b>{activeContact?.displayName}</b></header><div className="messages">{conversation.length?conversation.map((message)=><p key={message.id} className={message.fromMe?'from-me':'from-them'}>{message.body}<small>{new Date(message.createdAt).toLocaleString()}</small></p>):<div className="empty">Say hello with something you share.</div>}</div><form onSubmit={send}><textarea aria-label="Message" required maxLength={1500} value={body} onChange={(event)=>setBody(event.target.value)} placeholder="Write a respectful message…"/><button className="primary" disabled={busy||!body.trim()}><Send size={17}/>Send</button></form></div></div>:<div className="empty">Messaging opens only after a request is accepted.</div>}</section></>}
  <div className="info-box"><Shield size={22}/><p>This pilot uses self-selected age groups and hubs. Public launch still requires real verification and a staffed moderation process.</p></div></div></main>
}
