/* eslint-disable @next/next/no-img-element -- Local covers are precompressed; private media must retain same-origin session cookies. */
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { ArrowRight, ArrowUpRight, CalendarDays, Flower2, Leaf, MessageCircle, Users } from 'lucide-react';
import { getCurrentUser } from './auth';
import { Brand } from '@/components/social/ui';

export default async function HomePage() {
  if (await getCurrentUser()) redirect('/feed');
  return <main className="tv-landing"><header className="tv-landing-nav"><Link href="/" aria-label="Toveli home"><Brand/></Link><nav><a href="#how-it-feels">A different kind of social</a><Link href="/login">Sign in</Link><Link className="tv-btn primary" href="/login?mode=register">Find your people<ArrowUpRight size={16}/></Link></nav></header>
    <section className="tv-landing-hero"><div className="tv-landing-copy"><span className="tv-eyebrow"><span/>MADE FOR LIFE BEYOND THE FEED</span><h1>Less scrolling.<br/>More <em>belonging.</em></h1><p>Your campus is full of people you haven’t met yet. Find a little in common. Make a small plan. See where a hello takes you.</p><div className="tv-landing-cta"><Link href="/login?mode=register" className="tv-btn primary">Find my people<ArrowUpRight size={18}/></Link><Link href="/demo" className="tv-text-btn">Take a look around<ArrowRight size={17}/></Link></div><div className="tv-landing-promise"><Leaf size={17}/><span>A finite feed. Small circles. Real afternoons.</span></div></div><div className="tv-landing-visual"><img src="/campus.jpg" alt="A leafy path and a reason to take the scenic route"/><span className="tv-landing-photo-note">GOOD COMPANY IS CLOSER THAN YOU THINK.</span><div className="tv-landing-plan"><span className="tv-landing-plan-icon"><CalendarDays size={22}/></span><div><small>A LITTLE INSPIRATION</small><h3>A walk. A camera. A new friend.</h3><p>That’s a pretty good afternoon.</p></div><ArrowUpRight size={18}/></div><span className="tv-landing-orbit"><Flower2 size={67} strokeWidth={1.1}/></span></div></section>
    <section className="tv-landing-how" id="how-it-feels"><div><span className="tv-eyebrow">A SMALLER, BETTER KIND OF SOCIAL</span><h2>More than people to follow.<br/><em>People to do things with.</em></h2></div><div className="tv-landing-features">{[{ Icon: Users, title: 'Find your little corner.', text: 'Photography, coding, books, or a new curiosity. Small circles turn a shared interest into a familiar face.' }, { Icon: CalendarDays, title: 'Make “we should” happen.', text: 'A coffee after class. A study session. Simple plans with small groups and a public meeting spot.' }, { Icon: MessageCircle, title: 'A hello, at your pace.', text: 'Connect by mutual choice. Start with a shared interest. No pressure to reply instantly or perform for a crowd.' }].map(({ Icon, title, text }) => <article key={title}><span><Icon size={23} strokeWidth={1.6}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="tv-landing-bottom"><Leaf size={31} strokeWidth={1.3}/><h2>Your best moments happen <em>out there.</em></h2><p>Let’s help you find the people to share them with.</p><Link href="/login?mode=register" className="tv-btn primary">Start with a little hello<ArrowUpRight size={18}/></Link></section><footer className="tv-landing-footer"><Brand/><span>Made for more than scrolling.</span><Link href="/demo">Explore the interactive demo<ArrowUpRight size={15}/></Link></footer>
  </main>;
}
