'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, ArrowRight, Bell, Bookmark, BookOpen, CalendarDays, Camera, Check, ChevronRight, Clock3, Code2, Compass, Ellipsis, Heart, Home, Leaf, LockKeyhole, MapPin, MessageCircle, MoonStar, Pause, PenLine, Play, Plus, Search, Send, Settings, ShieldCheck, Sparkles, SunMedium, UserRoundSearch, Users, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Toaster, toast } from 'sonner';
import { circles, defaultProfile, hubs, interests, intents, people, rankPeople, seedPosts, type Post, type Profile } from '@/lib/model';

type View = 'feed'|'radar'|'circles'|'plans'|'chat'|'profile'|'onboard'|'settings';
type Match = ReturnType<typeof rankPeople>[number];
type Value = { text?:string; title?:string; place?:string; date?:string; size?:number; tag?:string; expiresAt?:number };
type Snapshot = { data:Record<string,Value>; profile:Profile; matches:Match[] };
type Modal = 'post'|'plan'|'pulse'|'match'|'short'|'report'|null;

const nav = [
  ['feed','Today',Home,'/feed'], ['radar','People',UserRoundSearch,'/radar'], ['circles','Circles',Users,'/circles'],
  ['plans','Plans',CalendarDays,'/plans'], ['chat','Messages',MessageCircle,'/chat/aarav'],
] as const;
const headings:Record<View,[string,string,string]> = {
  feed:['YOUR DAILY EDITION','Your people. Your place. Today.','A finite view of what matters around you.'],
  radar:['PEOPLE AROUND YOUR WORLD','Start with something in common.','Interest overlap is an introduction, not a judgment.'],
  circles:['SMALL GROUPS, SHARED ENERGY','Belong before you perform.','Join through an interest and let familiarity grow.'],
  plans:['FROM SOMETIME TO A REAL TIME','Make the next thing happen.','One activity, one public place, a few people.'],
  chat:['CONVERSATIONS WITH CONTEXT','Skip the empty hello.','Begin with the thing that brought you together.'],
  profile:['YOUR CORNER OF TOVELI','More person. Less performance.','Your interests, thoughts, circles, and plans in one place.'],
  onboard:['A BETTER STARTING POINT','Help Toveli understand enough.','You choose the signals and can change them anytime.'],
  settings:['YOUR SPACE, YOUR RULES','Control what Toveli knows.','Privacy and safety are available to everyone.'],
};
const initials=(name:string)=>name.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()||'T';
function Avatar({name,color='blue',size='md'}:{name:string;color?:string;size?:'sm'|'md'|'lg'|'xl'}){return <span className={`v3-avatar v3-${color} v3-${size}`}>{initials(name)}</span>}
function Logo(){return <Link className="v3-logo" href="/feed"><i>t</i>toveli<b>.</b></Link>}
function Picker({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="v3-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
function Empty({icon,title,copy,action}:{icon:React.ReactNode;title:string;copy:string;action?:()=>void}){return <section className="v3-empty"><span>{icon}</span><h2>{title}</h2><p>{copy}</p>{action&&<button className="v3-primary" onClick={action}>Create one<ArrowRight size={16}/></button>}</section>}

export default function Toveli({initialView,chatId}:{initialView:View;chatId?:string}){
  const [snap,setSnap]=useState<Snapshot>({data:{},profile:defaultProfile,matches:rankPeople(defaultProfile)});
  const [profile,setProfile]=useState<Profile>(defaultProfile);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<Match|null>(null),[text,setText]=useState(''),[tag,setTag]=useState(interests[0]);
  const [search,setSearch]=useState(''),[tab,setTab]=useState<'today'|'hub'|'saved'>('today'),[step,setStep]=useState(0);
  const [planTitle,setPlanTitle]=useState(''),[place,setPlace]=useState('Campus library'),[date,setDate]=useState(''),[size,setSize]=useState('4');
  const [used,setUsed]=useState(0),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(0);
  const [loadedAt]=useState(()=>Date.now());
  const lease=useRef(0),running=useRef(false);
  async function load(){setLoading(true);setError('');try{const [a,b]=await Promise.all([fetch('/api/state'),fetch('/api/shorts')]);if(a.status===401){location.href='/login';return}const s=await a.json() as Snapshot&{error?:string};if(!a.ok)throw Error(s.error||'Toveli could not load.');setSnap(s);setProfile(s.profile);if(b.ok){const x=await b.json() as {used:number};setUsed(x.used)}}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{const id=setTimeout(()=>void load(),0);return()=>clearTimeout(id)},[]);
  async function act(action:unknown,msg?:string){if(busy||loading)return false;setBusy(true);try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const s=await r.json() as Snapshot&{error?:string};if(!r.ok)throw Error(s.error||'Unable to save.');setSnap(s);if(msg)toast.success(msg);return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
  function open(kind:Exclude<Modal,null>,value=''){setText(value);setModal(kind)}
  function toggle(kind:'like'|'save'|'circle'|'request',id:string){void act({kind,id,enabled:!snap.data[`${kind}:${id}`]})}
  function match(m:Match){setSelected(m);setModal('match')}
  async function short(){if(running.current)return;running.current=true;try{const r=await fetch('/api/shorts',{method:'POST'});const x=await r.json() as {used:number;leaseUntil:number;error?:string};if(!r.ok)throw Error(x.error);lease.current=x.leaseUntil;setUsed(x.used);setPlaying(true)}catch(e){running.current=false;toast.error((e as Error).message)}}
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>{if(document.hidden||Date.now()>=lease.current){running.current=false;setPlaying(false)}else setFrame(Math.floor(Date.now()/1400)%3)},250);return()=>clearInterval(id)},[playing]);
  function closeModal(){running.current=false;setPlaying(false);setModal(null)}
  const data=snap.data;
  const mine=useMemo(()=>Object.entries(data).filter(([k])=>k.startsWith('post:')).reverse().map(([id,v])=>({id,author:snap.profile.name,text:v.text||'',tag:v.tag||'Writing',type:'text',color:'green'} as Post)),[data,snap.profile.name]);
  const posts=[...mine,...seedPosts].filter(p=>(tab!=='saved'||data[`save:${p.id}`])&&(tab!=='hub'||p.id!=='photo')&&[p.author,p.text,p.tag].join(' ').toLowerCase().includes(search.toLowerCase())).slice(0,5);
  const plans=Object.entries(data).filter(([k])=>k.startsWith('plan:'));
  const pulse=data.pulse?.expiresAt&&data.pulse.expiresAt>loadedAt?data.pulse.text:undefined;
  const current=snap.matches.find(m=>m.id===chatId)||snap.matches[0];
  const h=headings[initialView];
  return <div className="v3-app"><Toaster theme="dark" position="bottom-right"/>
    <aside className="v3-sidebar"><div className="v3-brand"><Logo/><span>PRIVATE BUILD</span></div><nav>{nav.map(([id,label,Icon,href])=><Link key={id} href={href} className={initialView===id?'active':''}><Icon/><span>{label}</span>{id==='radar'&&<i>New</i>}</Link>)}</nav><div className="v3-side-group"><p>YOUR CIRCLES</p>{circles.filter(c=>data[`circle:${c.id}`]).map(c=><Link href="/circles" key={c.id}><i className={`v3-dot v3-${c.color}`}/>{c.name}</Link>)}{!circles.some(c=>data[`circle:${c.id}`])&&<Link href="/circles" className="muted"><Plus/>Join your first circle</Link>}</div><div className="v3-side-card"><span className="v3-orbit"><i/><b/><em/></span><p>Your social life should give energy back.</p><Link href="/plans">Make a small plan<ArrowRight/></Link></div><footer><Link href="/settings"><Settings/>Settings</Link><Link href="/profile" className="v3-account"><Avatar name={snap.profile.name} color="green" size="sm"/><span><b>{snap.profile.name}</b><small>{snap.profile.intent}</small></span><ChevronRight/></Link></footer></aside>
    <div className="v3-stage"><header className="v3-top"><div><Logo/><span/><Link href="/onboard"><MapPin/>{snap.profile.hub}<ChevronRight/></Link></div><div><Link href="/community" className="v3-live"><i/>Live community</Link><button aria-label="Notifications"><Bell/></button><Link href="/profile"><Avatar name={snap.profile.name} color="green" size="sm"/></Link></div></header>
      <div className="v3-layout"><main className="v3-main">{error&&<div className="v3-error">{error}<button onClick={load}>Retry</button></div>}<header className="v3-page-head"><div><p>{h[0]}</p><h1>{h[1]}</h1><span>{h[2]}</span></div>{initialView==='feed'&&<button className="v3-primary" onClick={()=>open('post')}><PenLine/>Create</button>}{initialView==='plans'&&<button className="v3-primary" onClick={()=>open('plan')}><Plus/>New plan</button>}</header>
        {initialView==='feed'&&<><section className="v3-now"><div><span><SunMedium/>NOW AROUND YOU</span><h2>Three ways into your day.</h2><p>Choose a person, a group, or a simple plan. The feed can wait.</p></div><div><Link href="/radar"><i className="blue"><UserRoundSearch/></i><span><b>{snap.matches.length} people to explore</b><small>From your chosen interests</small></span><ChevronRight/></Link><Link href="/circles"><i className="pink"><Users/></i><span><b>{circles.length} circles near your hub</b><small>Small groups, easy starts</small></span><ChevronRight/></Link><button onClick={()=>{setPlanTitle('Something small after class');setModal('plan')}}><i className="green"><CalendarDays/></i><span><b>Make one plan real</b><small>Pick a public place and time</small></span><ChevronRight/></button></div></section>
          <section className="v3-pulses"><button onClick={()=>open('pulse',pulse||'')}><span><Avatar name={snap.profile.name} color="green"/><i><Plus/></i></span><small>{pulse||'Add your pulse'}</small></button>{people.slice(0,4).map((p,i)=><button key={p.id} onClick={()=>match(snap.matches.find(m=>m.id===p.id)||snap.matches[0])}><span><Avatar name={p.name} color={p.color}/></span><small>{['Photo walk?','Library later','Building today','Sky looks good'][i]}</small></button>)}<Link href="/community"><span><Users/></span><small>Live members</small></Link></section>
          <section className="v3-compose"><Avatar name={snap.profile.name} color="green"/><button onClick={()=>open('post')}>Share a thought, question, or invitation…</button><Camera/><button className="v3-compact" onClick={()=>open('post')}><PenLine/>Post</button></section>
          <div className="v3-toolbar"><div>{([['today','Today'],['hub','Your hub'],['saved','Saved']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><label><Search/><input aria-label="Search feed" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search today"/></label></div><p className="v3-note">Sample community content is labelled. Your posts stay in this private build.</p>
          <div className="v3-feed">{posts.map(p=><article className="v3-post" key={p.id}><header><Avatar name={p.author} color={p.color}/><div><b>{p.author}</b><span>{p.id.startsWith('post:')?'Your private post':'Sample post'} · {p.tag}</span></div><Ellipsis/></header><p>{p.text}</p>{p.type==='photo'&&<figure><Image src="/campus.jpg" width={1200} height={800} alt="Tree-lined university campus at sunset"/><figcaption>Outside is a good place to start. <a href="https://unsplash.com/photos/campus-buildings-surrounded-by-trees-at-sunset-xjmmQ06Iprw" target="_blank" rel="noreferrer">Kaden Taylor · Unsplash</a></figcaption></figure>}<footer><button className={data[`like:${p.id}`]?'active':''} onClick={()=>toggle('like',p.id)}><Heart fill={data[`like:${p.id}`]?'currentColor':'none'}/>{data[`like:${p.id}`]?'Liked':'Like'}</button><button onClick={()=>{setPlanTitle(p.tag==='Books'?'Bring a book afternoon':p.tag==='Coding'?'One-hour beginner build':'A short campus photo walk');setModal('plan')}}><CalendarDays/>Turn into a plan</button><button aria-label="Save" className={data[`save:${p.id}`]?'active':''} onClick={()=>toggle('save',p.id)}><Bookmark fill={data[`save:${p.id}`]?'currentColor':'none'}/></button></footer></article>)}{!posts.length&&<Empty icon={<Bookmark/>} title="Nothing here yet." copy="Save something or create the first post." action={()=>open('post')}/>}</div><section className="v3-end"><Leaf/><div><span>YOU REACHED THE END</span><h2>That is enough internet for now.</h2><p>Make a plan, message someone, or simply leave.</p></div><Link href="/plans">Do something together<ArrowRight/></Link></section></>}
        {initialView==='radar'&&<><div className="v3-search-row"><label><Search/><input aria-label="Search people" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search a person or interest"/></label><Link className="v3-secondary" href="/onboard"><Sparkles/>Tune interests</Link></div><div className="v3-context"><span><MapPin/>{snap.profile.hub}</span><span><ShieldCheck/>{snap.profile.cohort==='teen'?'Teen peer group':'Adult group'}</span><span><Compass/>{snap.profile.intent}</span></div><p className="v3-note">Sample profiles. The index measures visible factors and is not a friendship probability.</p><div className="v3-people">{snap.matches.filter(m=>[m.name,...m.interests].join(' ').toLowerCase().includes(search.toLowerCase())).map(m=><article key={m.id}><div className="v3-person-top"><span>{m.score}<small>/100</small></span><Avatar name={m.name} color={m.color} size="xl"/><i>SAMPLE</i></div><div className="v3-person-body"><h2>{m.name}</h2><span><MapPin/>{m.hub}</span><p>{m.bio}</p><div className="v3-tags">{m.shared.map(x=><i key={x}>{x}</i>)}</div><div className="v3-bars">{[['Interests',m.breakdown.interest,50],['Place',m.breakdown.hub,30],['Intent',m.breakdown.intent,20]].map(([label,n,max])=><span key={String(label)}><i><b style={{width:`${Number(n)/Number(max)*100}%`}}/></i><small>{label}</small><em>{n}/{max}</em></span>)}</div><button className="v3-secondary full" onClick={()=>match(m)}>{data[`request:${m.id}`]?<Check/>:<Compass/>}{data[`request:${m.id}`]?'Interest saved':'See why you connect'}<ArrowRight/></button></div></article>)}</div><section className="v3-community-banner"><div><span><i/>REAL PILOT MEMBERS</span><h2>Ready to test mutual connections?</h2><p>Messages open after both people accept.</p></div><Link href="/community">Open live community<ArrowRight/></Link></section></>}
        {initialView==='circles'&&<><section className="v3-circle-feature"><div><span><Users/>THIS WEEK AT YOUR HUB</span><h2>A photo walk with no pressure to be a photographer.</h2><p>Meet at the student activity centre. Walk for forty minutes. Bring any camera.</p><button className="v3-primary" onClick={()=>{setPlanTitle('Golden-hour campus photo walk');setModal('plan')}}><CalendarDays/>Add to plans</button></div><Image src="/campus.jpg" width={1200} height={800} alt="Tree-lined university campus at sunset"/></section><div className="v3-section-title"><div><p>FIND YOUR ROOM</p><h2>Circles built around doing.</h2></div><span>{circles.length} available</span></div><div className="v3-circles">{circles.map((c,i)=>{const Icon=i===0?Camera:i===1?Code2:BookOpen;const joined=Boolean(data[`circle:${c.id}`]);return <article className={`v3-${c.color}`} key={c.id}><div><Icon/><span>0{i+1}</span></div><section><small>{c.tag} · {c.members} SAMPLE MEMBERS</small><h2>{c.name}</h2><p>{c.description}</p><span><Clock3/>{['Thursday · Photo walk','Saturday · Tiny build','Sunday · Quiet reading'][i]}</span><button className={joined?'v3-secondary full':'v3-primary full'} onClick={()=>toggle('circle',c.id)}>{joined?<><Check/>Joined · Leave</>:<><Plus/>Join circle</>}</button></section></article>})}</div><section className="v3-principle"><MoonStar/><div><h2>Quiet participation counts.</h2><p>Read first, join when ready, and choose group activities if that feels easier.</p></div></section></>}
        {initialView==='plans'&&<><section className="v3-week"><div><span>THIS WEEK</span><b>{plans.length}</b><small>private plans</small></div><div><span>A GOOD FIRST PLAN</span><p>Short, specific, public, and easy to leave.</p></div></section>{plans.length?<div className="v3-plans">{plans.map(([id,p])=>{const d=p.date?new Date(p.date):null;return <article key={id}><div><span>{d?.toLocaleDateString(undefined,{month:'short'})}</span><b>{d?.getDate()}</b><small>{d?.toLocaleDateString(undefined,{weekday:'short'})}</small></div><i/><section><small>PRIVATE DRAFT · UP TO {p.size} PEOPLE</small><h2>{p.title}</h2><p><MapPin/>{p.place}<Clock3/>{d?.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</p></section><button onClick={()=>void act({kind:'delete',id},'Plan removed.')}>Remove</button></article>})}</div>:<Empty icon={<CalendarDays/>} title="Give the idea a time." copy="A plan can be as small as one hour in the library." action={()=>open('plan')}/>}<section className="v3-safety"><ShieldCheck/><div><h2>First plans stay in public places.</h2><p>Choose a staffed campus location, keep your own way home, and change your mind when needed.</p></div></section></>}
        {initialView==='chat'&&current&&<><p className="v3-note">Rehearsal with sample profiles. Drafts stay private and nothing is sent.</p><div className="v3-chat"><aside>{snap.matches.map(m=><Link href={`/chat/${m.id}`} key={m.id} className={current.id===m.id?'active':''}><Avatar name={m.name} color={m.color}/><span><b>{m.name}</b><small>{m.shared[0]||'Something new'}</small></span></Link>)}</aside><section><header><Avatar name={current.name} color={current.color}/><span><b>{current.name}</b><small>Sample profile · rehearsal</small></span><Ellipsis/></header><div className="v3-ice"><Sparkles/><section><small>START WITH THE SHARED THING</small><p>“Hey, I noticed we both enjoy {current.shared[0]?.toLowerCase()||'trying new things'}. What got you into it?”</p><button onClick={()=>setText(`Hey, I noticed we both enjoy ${current.shared[0]?.toLowerCase()||'trying new things'}. What got you into it?`)}>Use this starter<ArrowRight/></button></section></div><div className="v3-thread">{data[`draft:${current.id}`]?.text?<p>{data[`draft:${current.id}`].text}<small>Saved draft · not sent</small></p>:<div><MessageCircle/><b>Write something you would actually say.</b><small>You can edit it before a real conversation exists.</small></div>}</div><form onSubmit={async e=>{e.preventDefault();if(await act({kind:'draft',id:current.id,text},'Draft saved.'))setText('')}}><textarea required maxLength={1500} value={text} onChange={e=>setText(e.target.value)} placeholder="Draft your introduction…"/><button className="v3-primary" disabled={busy||!text.trim()}><Bookmark/>Save draft</button></form></section></div><Link className="v3-real-chat" href="/community"><span><i/>LIVE COMMUNITY MESSAGES</span><b>Real messages open after mutual acceptance.</b><ArrowRight/></Link></>}
        {initialView==='profile'&&<><section className="v3-profile"><div className="v3-cover"><span className="v3-orbit"><i/><b/><em/></span></div><header><Avatar name={snap.profile.name} color="green" size="xl"/><div><h2>{snap.profile.name}</h2><p><MapPin/>{snap.profile.hub}</p></div><Link className="v3-secondary" href="/onboard">Edit profile</Link></header><section><p>{pulse||'Add a short pulse so people know what you are open to today.'}</p><button onClick={()=>open('pulse',pulse||'')}>{pulse?'Edit pulse':'Add pulse'}<PenLine/></button><div className="v3-tags">{snap.profile.interests.map(x=><i key={x}>{x}</i>)}</div></section><footer>{[[mine.length,'Posts'],[plans.length,'Plans'],[Object.keys(data).filter(k=>k.startsWith('save:')).length,'Saved'],[circles.length,'Circles']].map(([n,l])=><span key={String(l)}><b>{n}</b>{l}</span>)}</footer></section><div className="v3-profile-grid"><Link href="/feed"><PenLine/><b>Your posts</b><span>{mine.length} created</span><ChevronRight/></Link><Link href="/plans"><CalendarDays/><b>Your plans</b><span>{plans.length} drafts</span><ChevronRight/></Link><Link href="/circles"><Users/><b>Your circles</b><span>Find your room</span><ChevronRight/></Link><Link href="/settings"><LockKeyhole/><b>Privacy</b><span>Control your signals</span><ChevronRight/></Link></div></>}
        {initialView==='onboard'&&<section className="v3-onboard"><div className="v3-stepper">{['Place','Interests','Intent'].map((x,i)=><span key={x} className={i<=step?'active':''}><i>{i<step?<Check/>:i+1}</i><b>{x}</b></span>)}</div>{step===0&&<div className="v3-onboard-panel"><i><MapPin/></i><h2>Where does your real life happen?</h2><p>A broad hub is enough. Live location is not needed.</p><label>Name people will see<input maxLength={40} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Primary hub<Picker label="Primary hub" value={profile.hub} values={hubs} onChange={hub=>setProfile({...profile,hub})}/></label><label>Discovery group<Picker label="Discovery group" value={profile.cohort==='teen'?'Teen peers (16–17)':'Adults (18+)'} values={['Teen peers (16–17)','Adults (18+)']} onChange={v=>setProfile({...profile,cohort:v.startsWith('Teen')?'teen':'adult'})}/></label><small>Public launch requires actual verification.</small></div>}{step===1&&<div className="v3-onboard-panel"><i><Compass/></i><h2>What would you enjoy sharing?</h2><p>Visible starting points, not a personality test.</p><div className="v3-interests">{interests.map((x,i)=>{const chosen=profile.interests.includes(x);return <button key={x} className={chosen?'active':''} onClick={()=>setProfile({...profile,interests:chosen?profile.interests.filter(y=>y!==x):[...profile.interests,x]})}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{chosen?<Check/>:<Plus/>}</button>})}</div></div>}{step===2&&<div className="v3-onboard-panel"><i><Users/></i><h2>What would make Toveli useful now?</h2><p>Your intent can change as your life changes.</p><label>I want to…<Picker label="Intent" value={profile.intent} values={intents} onChange={intent=>setProfile({...profile,intent})}/></label><div className="v3-setting"><span><b>Take it slow</b><small>Prioritise circles and group activities.</small></span><Switch checked={profile.introvert} onCheckedChange={introvert=>setProfile({...profile,introvert})}/></div><div className="v3-setting disabled"><span><b>Learn from feed activity</b><small>Unavailable. Likes do not change matches.</small></span><Switch disabled checked={false}/></div></div>}<footer>{step>0&&<button className="v3-secondary" onClick={()=>setStep(step-1)}><ArrowLeft/>Back</button>}{step<2?<button className="v3-primary" onClick={()=>setStep(step+1)} disabled={!profile.name.trim()||!profile.interests.length}>Continue<ArrowRight/></button>:<button className="v3-primary" disabled={busy||loading} onClick={async()=>{if(await act({kind:'profile',data:profile},'Starting point updated.'))location.href='/radar'}}>Save and discover<ArrowRight/></button>}</footer></section>}
        {initialView==='settings'&&<div className="v3-settings"><section><header><i><Compass/></i><span><h2>Discovery</h2><p>Change what Toveli prioritises.</p></span></header><label>Current intent<Picker label="Intent" value={profile.intent} values={intents} onChange={intent=>setProfile({...profile,intent})}/></label><div className="v3-setting"><span><b>Take it slow</b><small>Show circles before direct suggestions.</small></span><Switch checked={profile.introvert} onCheckedChange={introvert=>setProfile({...profile,introvert})}/></div><button className="v3-primary" onClick={()=>void act({kind:'profile',data:profile},'Settings saved.')}>Save settings</button></section><section><header><i><LockKeyhole/></i><span><h2>Privacy and signals</h2><p>Private Saathi content stays outside discovery.</p></span></header><div className="v3-boundaries"><span><Check/>Selected interests can shape discovery.</span><span><Check/>Hub and intent can shape discovery.</span><span><X/>Private messages are not matching inputs.</span><span><X/>Journals and mood check-ins are not imported.</span><span><X/>Watch-history learning is disabled.</span></div></section><section><header><i><Clock3/></i><span><h2>Short-content allowance</h2><p>{Math.floor(used/60)} of 20 minutes reserved today.</p></span></header><Progress value={used/12}/><small>Paid plans cannot extend this allowance.</small></section><section><header><i><LockKeyhole/></i><span><h2>Account</h2><p>End this session on the current device.</p></span></header><button className="v3-secondary" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}}>Sign out</button></section></div>}
      </main><aside className="v3-right"><section className="v3-balance"><header><span><Leaf/>Shorts allowance</span><b>{Math.floor(used/60)}<small>/20 min</small></b></header><Progress value={used/12}/><p>Short entertainment has a boundary. The rest of Toveli stays open.</p><button onClick={()=>setModal('short')}><Play/>Open five-second preview</button></section><section className="v3-good"><header><span><small>GOOD STARTS</small><h2>{snap.profile.introvert?'A circle first':'People worth a hello'}</h2></span><Link href={snap.profile.introvert?'/circles':'/radar'}><ArrowRight/></Link></header>{snap.profile.introvert?<Link className="v3-slow" href="/circles"><Users/><b>Join through a hobby.</b><p>Read first. Participate when ready.</p></Link>:snap.matches.slice(0,2).map(m=><button key={m.id} onClick={()=>match(m)}><Avatar name={m.name} color={m.color}/><span><b>{m.name}</b><small>{m.shared.slice(0,2).join(' · ')||'A new perspective'}</small></span><i>{m.score}</i></button>)}</section><section className="v3-next"><span>ONE SMALL THING</span><h2>Turn an “I should” into Thursday.</h2><p>Draft one hour in a public campus place.</p><button className="v3-secondary full" onClick={()=>{setPlanTitle('A one-hour study session');setModal('plan')}}>Make a plan<CalendarDays/></button></section><footer><Link href="/settings">Privacy</Link><span>·</span><Link href="/community">Community</Link><p>Designed to let you leave.</p></footer></aside></div></div>
    <nav className="v3-mobile">{nav.map(([id,label,Icon,href])=><Link key={id} href={href} className={initialView===id?'active':''}><Icon/><span>{label}</span></Link>)}</nav>
    <Dialog open={modal!==null} onOpenChange={v=>{if(!v)closeModal()}}><DialogContent className="v3-dialog"><DialogTitle>{modal==='post'?'Share something worth responding to.':modal==='plan'?'Give the idea a place and time.':modal==='pulse'?'What are you open to today?':modal==='match'?'A starting point, clearly explained.':modal==='short'?'A short that knows when to stop.':'Report this sample profile.'}</DialogTitle><DialogDescription>{modal==='post'?'A thought, question, invitation, or useful find.':modal==='plan'?'A private draft. No invitation is sent.':modal==='pulse'?'Optional and gone after 24 hours.':modal==='match'?'Visible interests, place, and intent.':modal==='short'?'Each play reserves five seconds.':'Stored as a private test report.'}</DialogDescription>
      {modal==='post'&&<form onSubmit={async e=>{e.preventDefault();if(await act({kind:'post',text,tag},'Post created.'))setModal(null)}}><textarea required maxLength={1200} value={text} onChange={e=>setText(e.target.value)} placeholder="What could start a good conversation?"/><div><Picker label="Interest" value={tag} values={interests} onChange={setTag}/><span>{text.length}/1200</span></div><button className="v3-primary full" disabled={busy||!text.trim()}>Create post<Send/></button></form>}
      {modal==='pulse'&&<form onSubmit={async e=>{e.preventDefault();if(await act({kind:'pulse',text},'Pulse shared for 24 hours.'))setModal(null)}}><div className="v3-examples"><button type="button" onClick={()=>setText('Open to a study session after class')}>Study after class</button><button type="button" onClick={()=>setText('Anyone up for a short photo walk?')}>Photo walk</button><button type="button" onClick={()=>setText('Looking for a small project idea')}>Build something</button></div><textarea className="short" required maxLength={80} value={text} onChange={e=>setText(e.target.value)} placeholder="Open to…"/><div><span>Private build</span><span>{text.length}/80</span></div><button className="v3-primary full" disabled={busy||!text.trim()}>Share for 24 hours<Clock3/></button>{data.pulse&&<button type="button" className="v3-text" onClick={async()=>{if(await act({kind:'remove_pulse'},'Pulse removed.'))setModal(null)}}>Remove current pulse</button>}</form>}
      {modal==='plan'&&<form onSubmit={async e=>{e.preventDefault();if(await act({kind:'plan',title:planTitle,place,date:new Date(date).toISOString(),size:Number(size)},'Plan saved.'))setModal(null)}}><label>What is the plan?<input required minLength={3} maxLength={100} value={planTitle} onChange={e=>setPlanTitle(e.target.value)} placeholder="A photo walk after class"/></label><label>Public meeting place<Picker label="Meeting place" value={place} values={['Campus library','Campus café','Student activity centre']} onChange={setPlace}/></label><div className="v3-split"><label>Date and time<input required type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Group size<Picker label="Group size" value={size} values={['3','4','5','6','8','10','12']} onChange={setSize}/></label></div><button className="v3-primary full" disabled={busy}>Save plan<CalendarDays/></button></form>}
      {modal==='match'&&selected&&<div className="v3-match"><header><Avatar name={selected.name} color={selected.color} size="lg"/><span><h2>{selected.name}</h2><p><MapPin/>{selected.hub} · Sample</p></span><b>{selected.score}<small>/100</small></b></header><p>{selected.bio}</p><div>{[['Shared interests',selected.breakdown.interest,50],['Shared place',selected.breakdown.hub,30],['Shared intent',selected.breakdown.intent,20]].map(([l,n,max])=><span key={String(l)}><small>{l}</small><b>{n}/{max}</b></span>)}</div><em>No private messages, journals, or exact watch history are used.</em><button className="v3-primary full" onClick={()=>toggle('request',selected.id)}>{data[`request:${selected.id}`]?<><Check/>Interest saved · Undo</>:<><Plus/>Interested in connecting</>}</button><Link className="v3-secondary full" href={`/chat/${selected.id}`}>Draft an introduction<MessageCircle/></Link><button className="v3-text" onClick={async()=>{if(await act({kind:'block',id:selected.id,enabled:true},'Profile hidden.'))setModal(null)}}>Hide profile</button></div>}
      {modal==='short'&&<div className="v3-short"><div className={playing?'active':''}><span>A FIVE-SECOND MOMENT</span><h2>{playing?['Look up.','Notice one thing.','Share it with someone.'][frame]:'Entertainment with an ending.'}</h2><span className="v3-orbit"><i/><b/><em/></span></div><Progress value={used/12}/><p>{used} of 1200 seconds reserved today</p><button className="v3-primary full" disabled={used>=1200} onClick={playing?()=>{running.current=false;setPlaying(false)}:short}>{playing?<><Pause/>Pause</>:<><Play/>Play five seconds</>}</button><Link className="v3-secondary full" href="/radar">Find a person instead<ArrowRight/></Link></div>}
    </DialogContent></Dialog>
  </div>
}
