'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, Check, MessageCircle, Send, Shield, Sparkles, X } from 'lucide-react';
import { sharedInterests, type SocialAction, type SocialSnapshot, type Member } from '@/lib/social/types';
import { Avatar, Empty, relativeTime } from './ui';

export function Messages({ data, selectedId, choose, busy, mutate, openPerson, search, discover, demo }: { data: SocialSnapshot; selectedId?: string; choose: (id?: string) => void; busy: boolean; mutate: (a: SocialAction, msg?: string) => Promise<boolean>; openPerson: (p: Member) => void; search: string; discover: () => void; demo: boolean }) {
  const [body, setBody] = useState('');
  const [showStarters, setShowStarters] = useState(false);
  const bottom = useRef<HTMLDivElement>(null);
  const selected = data.contacts.find(p => p.id === selectedId);
  const messages = data.messages.filter(m => m.personId === selectedId);
  const requests = data.requests.filter(r => r.state === 'pending');
  const people = data.contacts.filter(p => p.name.toLowerCase().includes(search.toLowerCase()));
  const shared = data.me && selected ? sharedInterests(data.me, selected) : [];
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }, [messages.length, selectedId]);
  async function send(event: FormEvent) {
    event.preventDefault();
    if (selected && await mutate({ kind: 'message', personId: selected.id, body })) setBody('');
  }
  return <div className={`tv-inbox tv-card ${selected ? 'has-conversation' : ''}`}><aside className="tv-conversations"><div className="tv-inbox-heading"><h3>Messages</h3><span>{data.contacts.length}</span></div>
      {requests.length > 0 && <section className="tv-requests"><span className="tv-eyebrow">CONNECTION REQUESTS · {requests.length}</span>{requests.map(r => <div className="tv-request" key={r.id}><div className="tv-row"><Avatar person={r.person} size="sm" onClick={() => openPerson(r.person)}/><div><strong>{r.person.name}</strong><small>{r.direction === 'incoming' ? 'Wants to connect' : 'Waiting for their reply'}</small></div></div><div className="tv-row">{r.direction === 'incoming' ? <><button className="tv-btn primary small" disabled={busy} onClick={() => void mutate({ kind: 'respond', id: r.id, accept: true }, 'Connection accepted. Say hello!')}><Check size={14}/>Accept</button><button className="tv-icon-btn" disabled={busy} onClick={() => void mutate({ kind: 'respond', id: r.id, accept: false }, 'Request declined.')} aria-label={`Decline ${r.person.name}`}><X size={16}/></button></> : <button className="tv-text-btn" disabled={busy} onClick={() => void mutate({ kind: 'cancel_request', id: r.id }, 'Request cancelled.')}>Cancel request</button>}</div></div>)}</section>}
      {people.map(p => { const last = data.messages.filter(m => m.personId === p.id).at(-1); return <button className={`tv-conversation ${selected?.id === p.id ? 'active' : ''}`} key={p.id} onClick={() => choose(p.id)}><Avatar person={p}/><div><strong>{p.name}</strong><p>{last ? `${last.fromMe ? 'You: ' : ''}${last.body}` : 'You’re connected. Say hello.'}</p></div>{last && <small>{relativeTime(last.createdAt)}</small>}</button>; })}
      {!people.length && <div className="tv-inbox-empty"><p>{search ? 'No conversations match your search.' : 'Your next good conversation starts with a connection.'}</p><button className="tv-text-btn" onClick={discover}>Find your people →</button></div>}
    </aside><section className="tv-chat-panel">{selected ? <><header className="tv-chat-header"><button className="tv-icon-btn tv-chat-back" onClick={() => choose()} aria-label="Back to conversations"><ArrowLeft size={20}/></button><Avatar person={selected}/><button className="tv-chat-person" onClick={() => openPerson(selected)}><strong>{selected.name}</strong><small>{selected.hub} · View profile</small></button><Shield size={18}/></header><div className="tv-message-list"><div className="tv-chat-intro"><Avatar person={selected} size="lg"/><h3>You’re in good company.</h3><p>{shared.length ? `You both enjoy ${shared.join(' and ')}. That’s a good place to start.` : 'A small hello can turn into a good conversation.'}</p>{demo && <small>Demo conversation. Sample members don’t send live replies.</small>}</div>{messages.map(m => <div className={`tv-message ${m.fromMe ? 'mine' : ''}`} key={m.id}><p>{m.body}</p><time>{new Date(m.createdAt).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</time></div>)}<div ref={bottom}/></div><div className="tv-chat-compose">{showStarters && <div className="tv-starters"><small>Pick a starting point, then make it yours.</small>{[`What got you into ${shared[0]?.toLowerCase() || 'your favourite hobby'}?`, 'What’s something you’re excited to learn this week?', 'Any good campus spots you’d recommend?'].map(text => <button key={text} onClick={() => { setBody(text); setShowStarters(false); }}>{text}</button>)}</div>}<form className="tv-message-form" onSubmit={send}><button type="button" className="tv-icon-btn" aria-label="Conversation starters" aria-expanded={showStarters} onClick={() => setShowStarters(!showStarters)}><Sparkles size={19}/></button><label className="tv-sr-only" htmlFor="message-body">Message {selected.name}</label><textarea id="message-body" placeholder="A little hello goes a long way…" rows={1} value={body} maxLength={1500} onChange={e => setBody(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (body.trim() && !busy) e.currentTarget.form?.requestSubmit(); } }}/><button className="tv-icon-btn primary" disabled={busy || !body.trim()} aria-label="Send message"><Send size={18}/></button></form><small>No pressure to reply instantly. Good conversations take their own time.</small></div></> : <Empty icon={<MessageCircle/>} title="Room for a good conversation." text="Choose a connection, or find someone who shares your interests. Messages open after you both agree to connect." action="Discover people" onAction={discover}/>}</section></div>;
}
