/* eslint-disable @next/next/no-img-element -- Local covers are precompressed; private media must retain same-origin session cookies. */
'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, Bell, Bookmark, CalendarDays, Camera, Check, ChevronDown, Compass, Download, Flower2, Heart, Home, ImagePlus, Leaf, LoaderCircle, LogOut, MapPin, MessageCircle, Plus, RefreshCw, Search, Settings2, Shield, Sparkles, Users, X } from 'lucide-react';
import { interests } from '@/lib/model';
import { coverSrc, sharedInterests, type ItemKind, type Member, type SocialItem, type View } from '@/lib/social/types';
import { Avatar, Brand, Empty, Modal, Tag, ModalErrorContext, relativeTime } from './ui';
import { CircleCard, PlanCard, PostCard, type CardActions } from './cards';
import { Composer } from './composer';
import { ItemDetail, PersonDetail } from './details';
import { ProfileEditor } from './profile-editor';
import { Messages } from './messages';
import { useSocial } from './use-social';

const routes: Record<View, string> = { feed: '/feed', radar: '/radar', circles: '/circles', plans: '/plans', chat: '/messages', profile: '/profile', onboard: '/onboard', settings: '/settings', saved: '/saved', notifications: '/notifications' };
const navigation = [
  { view: 'feed' as View, label: 'Your feed', icon: Home }, { view: 'radar' as View, label: 'Discover people', icon: Compass },
  { view: 'circles' as View, label: 'Circles', icon: Users }, { view: 'plans' as View, label: 'Make plans', icon: CalendarDays },
  { view: 'chat' as View, label: 'Messages', icon: MessageCircle },
];
const headings: Record<View, [string, string, string]> = {
  feed: ['A LITTLE CLOSER TO YOUR PEOPLE', 'Your campus, in good company.', 'A few good moments. A few new faces. Something to look forward to.'],
  radar: ['FAMILIAR INTERESTS. NEW FACES.', 'Your kind of people.', 'Meet through something you already care about. Start with a little hello.'],
  circles: ['SMALL CIRCLES. MORE BELONGING.', 'Find your little corner.', 'For the things you could talk about for hours. And people who get it.'],
  plans: ['LESS “WE SHOULD”. MORE “LET’S”.', 'Good things are happening.', 'Simple plans, small groups, and a reason to put your phone away.'],
  chat: ['A LITTLE HELLO GOES A LONG WAY', 'Keep the conversation going.', 'Your people, at your pace.'],
  profile: ['YOUR CORNER OF THE CAMPUS', 'A little more you.', 'Your moments, your circles, and what comes next.'],
  onboard: ['LET’S MAKE YOURSELF AT HOME', 'Start with what you love.', 'Your next connection could be closer than you think.'],
  settings: ['MAKE TOVELI YOURS', 'A little space to breathe.', 'Your profile, preferences, and account.'],
  saved: ['GOOD THINGS, KEPT CLOSE', 'For another moment.', 'The posts, circles, and plans you wanted to come back to.'],
  notifications: ['FROM YOUR LITTLE WORLD', 'You’re part of something.', 'New replies, connections, and people joining your plans.'],
};

export default function SocialApp({ initialView = 'feed', chatId, demo = false }: { initialView?: View; chatId?: string; demo?: boolean }) {
  const router = useRouter();
  const state = useSocial(demo);
  const { data, loading, busy, error, toast, mutate, setToast, setError } = state;
  const [view, setView] = useState<View>(initialView);
  const [search, setSearch] = useState('');
  const [topic, setTopic] = useState('All');
  const [tab, setTab] = useState('');
  const [compose, setCompose] = useState<ItemKind | null>(null);
  const [detail, setDetail] = useState<string | null>(null);
  const [person, setPerson] = useState<Member | null>(null);
  const [manage, setManage] = useState<{ item?: SocialItem; person?: Member; action: 'delete' | 'report' | 'block' } | null>(null);
  const [selectedChat, setSelectedChat] = useState<string | undefined>(chatId);
  const [moreOpen, setMoreOpen] = useState(false);
  const [confirmLogout, setConfirmLogout] = useState(false);
  const hashOpened = useRef(false);

  function navigate(next: View, id?: string) {
    setDetail(null); setPerson(null); setMoreOpen(false); setSearch(''); setTopic('All'); setTab('');
    if (demo) { setView(next); setSelectedChat(id); window.scrollTo({ top: 0, behavior: 'smooth' }); }
    else router.push(next === 'chat' && id ? `/chat/${id}` : routes[next]);
  }
  useEffect(() => {
    if (!data || hashOpened.current) return;
    hashOpened.current = true;
    const id = window.location.hash.slice(1);
    if (id && data.items.some(i => i.id === id)) {
      // A share link's fragment is available only after browser hydration.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setDetail(id);
    }
  }, [data]);
  const actualView = data && !data.me ? 'onboard' : demo ? view : initialView;
  const me = data?.me;
  const now = data?.now ?? 0;
  const currentItem = data?.items.find(i => i.id === detail);
  const currentPerson = person && (data?.people.find(p => p.id === person.id) ?? data?.contacts.find(p => p.id === person.id) ?? (me?.id === person.id ? me : person));
  const unread = data?.notifications.filter(n => !n.read).length ?? 0;
  const pending = data?.requests.filter(r => r.direction === 'incoming' && r.state === 'pending').length ?? 0;
  const joined = data?.items.filter(i => i.kind === 'circle' && i.joined) ?? [];
  const upcoming = data?.items.filter(i => i.kind === 'plan' && (i.startsAt ?? 0) > now).sort((a, b) => (a.startsAt ?? 0) - (b.startsAt ?? 0)) ?? [];

  async function share(item: SocialItem) {
    try {
      if (demo) { await navigator.clipboard.writeText(`${item.title || item.author.name + ' on Toveli'}\n${item.body}`); setToast('Sample content copied. Demo actions stay in this browser.'); }
      else { await navigator.clipboard.writeText(`${location.origin}/${item.kind === 'post' ? 'feed' : item.kind === 'circle' ? 'circles' : 'plans'}#${item.id}`); setToast('Link copied. Members of your campus and age group can open it.'); }
    } catch { setError('Clipboard access is unavailable. You can select and copy the text instead.'); }
  }
  const actions: CardActions = { now, mutate, busy, openItem: item => setDetail(item.id), openPerson: setPerson, share: item => void share(item), manage: (item, action) => { setDetail(null); setManage({ item, action }); } };
  function exportData() {
    if (!data) return;
    const owned = { profile: data.me, posts: data.items.filter(i => i.mine), saved: data.items.filter(i => i.saved).map(i => i.id), joined: data.items.filter(i => i.joined).map(i => i.id), connections: data.requests, messages: data.messages };
    const url = URL.createObjectURL(new Blob([JSON.stringify(owned, null, 2)], { type: 'application/json' }));
    const a = document.createElement('a'); a.href = url; a.download = 'toveli-current-data.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    setToast('Downloaded your currently loaded profile and activity.');
  }
  const filterItem = (i: SocialItem) => (topic === 'All' || i.topic === topic) && `${i.title || ''} ${i.body} ${i.topic} ${i.author.name}`.toLowerCase().includes(search.toLowerCase());
  function renderTabs(options: string[]) {
    return <div className="tv-tabs" role="group" aria-label="Filter this view">{options.map((option, n) => <button key={option} aria-pressed={tab === option || (!tab && n === 0)} className={tab === option || (!tab && n === 0) ? 'active' : ''} onClick={() => setTab(option)}>{option}</button>)}</div>;
  }
  function renderTopicFilters() { return <div className="tv-topics" role="group" aria-label="Filter by interest">{['All', ...interests].map(t => <button key={t} className={t === topic ? 'selected' : ''} aria-pressed={t === topic} onClick={() => setTopic(t)}>{t === 'All' && <Sparkles size={13}/>} {t === 'All' ? 'For every interest' : t}</button>)}</div>; }
  function ActivityGrid({ items, emptyTitle, emptyText, create }: { items: SocialItem[]; emptyTitle: string; emptyText: string; create?: ItemKind }) {
    return items.length ? <div className="tv-activity-grid">{items.map(i => i.kind === 'circle' ? <CircleCard key={i.id} item={i} actions={actions}/> : i.kind === 'plan' ? <PlanCard key={i.id} item={i} actions={actions}/> : <PostCard key={i.id} item={i} actions={actions}/>)}</div> : <Empty title={emptyTitle} text={emptyText} action={create ? `Start a ${create}` : search || topic !== 'All' ? 'Clear filters' : 'Explore your campus'} onAction={() => { if (create) setCompose(create); else if (search || topic !== 'All') { setSearch(''); setTopic('All'); } else navigate('feed'); }}/>;
  }
  function renderRail() {
    if (!data || !me) return null;
    return <aside className="tv-right-rail"><section className="tv-card tv-rail-card"><div className="tv-row between"><h3>A little in common</h3><Compass size={17}/></div><p className="tv-muted tv-rail-subtitle">New faces. Familiar interests.</p>{data.people.slice(0, 3).map(p => <div className="tv-rail-person" key={p.id}><Avatar person={p} onClick={() => setPerson(p)}/><div><button className="tv-person-name" onClick={() => setPerson(p)}>{p.name}</button><small>{sharedInterests(me, p).slice(0, 2).join(' · ') || p.interests.slice(0, 2).join(' · ')}</small></div><button className="tv-icon-btn" onClick={() => setPerson(p)} aria-label={`Meet ${p.name}`}><ArrowUpRight size={18}/></button></div>)}{!data.people.length && <p className="tv-small-copy">Your campus is just getting started. A first post gives the next person a reason to say hello.</p>}<button className="tv-rail-link" onClick={() => navigate('radar')}>Find your people<ArrowRight size={16}/></button></section>
      <section className="tv-card tv-rail-card"><div className="tv-row between"><h3>Off the screen</h3><CalendarDays size={17}/></div><p className="tv-muted tv-rail-subtitle">Make room for a good afternoon.</p>{upcoming.slice(0, 2).map(item => <button key={item.id} className="tv-mini-plan" onClick={() => setDetail(item.id)}><span className="tv-mini-date"><small>{new Date(item.startsAt!).toLocaleDateString('en-IN', { month: 'short' })}</small><b>{new Date(item.startsAt!).getDate()}</b></span><span><strong>{item.title}</strong><small>{item.place}</small><em>{item.joined ? 'You’re going' : `${Math.max(0, (item.capacity ?? 0) - item.members)} spaces open`}</em></span></button>)}{!upcoming.length && <p className="tv-small-copy">A coffee, a study session, a walk. It doesn’t have to be a big occasion.</p>}<button className="tv-rail-link" onClick={() => upcoming.length ? navigate('plans') : setCompose('plan')}>{upcoming.length ? 'See what’s happening' : 'Make the first plan'}<ArrowRight size={16}/></button></section>
      <div className="tv-breathe-card"><Flower2 size={31} strokeWidth={1.3}/><span className="tv-eyebrow">A LITTLE REMINDER</span><h3>Your best moments<br/>happen out there.</h3><p>Your feed has an ending.<br/>Your afternoon doesn’t have to.</p><button onClick={() => navigate('plans')}>Find a reason to step out<ArrowUpRight size={16}/></button></div><footer className="tv-rail-footer"><span>Toveli · Made for more than scrolling.</span><button onClick={() => navigate('settings')}>Your preferences</button></footer>
    </aside>;
  }
  function renderContent() {
    if (!data) return null;
    if (actualView === 'onboard') return <ProfileEditor me={me ?? null} accountName={data.account.name} busy={busy} mutate={mutate} onDone={() => navigate('feed')}/>;
    if (actualView === 'settings') return <div className="tv-settings-layout"><ProfileEditor me={me!} accountName={data.account.name} busy={busy} mutate={mutate} onDone={() => {}}/><section className="tv-card tv-account-card"><h3>Your account</h3><p>Keep a copy of your currently loaded activity. This includes up to 80 recent campus items and 200 messages, with your own activity selected for export.</p><button className="tv-btn secondary" onClick={exportData}><Download size={17}/>Download current data</button>{demo ? <button className="tv-btn secondary" onClick={state.resetDemo}><RefreshCw size={17}/>Reset sample content</button> : <button className="tv-btn secondary" onClick={() => setConfirmLogout(true)}><LogOut size={17}/>Sign out</button>}<div className="tv-note"><Shield size={17}/><span>Your precise location isn’t collected. Age groups are separated. A connection needs mutual acceptance before messaging opens.</span></div></section></div>;
    if (actualView === 'chat') return <Messages key={demo ? selectedChat : chatId} data={data} demo={demo} selectedId={demo ? selectedChat : chatId} choose={id => { if (demo) setSelectedChat(id); else navigate('chat', id); }} busy={busy} mutate={mutate} openPerson={setPerson} search={search} discover={() => navigate('radar')}/>;
    if (actualView === 'notifications') return <section className="tv-card tv-notifications"><div className="tv-row between"><h3>Your activity</h3><button className="tv-text-btn" disabled={busy || !unread} onClick={() => void mutate({ kind: 'read_notifications' }, 'All caught up.')}><Check size={16}/>Mark all read</button></div>{data.notifications.length ? data.notifications.filter(n => n.text.toLowerCase().includes(search.toLowerCase())).map(n => <button className={`tv-notification ${n.read ? '' : 'unread'}`} key={n.id} onClick={() => { const id = n.target.split('#')[1]; if (id) { if (data.items.some(i => i.id === id)) setDetail(id); else setToast('This item is no longer in your recent campus feed.'); } else if (n.target === '/plans' || n.target === '/circles') navigate(n.target.slice(1) as View); else navigate('chat', n.target.startsWith('/chat/') ? n.target.split('/').at(-1) : undefined); }}><span className="tv-notification-icon"><Bell size={19}/></span><span><strong>{n.text}</strong><small>{relativeTime(n.createdAt)}</small></span>{!n.read && <i/>}<ArrowUpRight size={17}/></button>) : <Empty icon={<Bell/>} title="A quiet moment." text="When someone connects, replies, or joins your plan, you’ll see it here."/>}</section>;
    if (actualView === 'radar') {
      const people = data.people.filter(p => (topic === 'All' || p.interests.includes(topic)) && `${p.name} ${p.bio} ${p.interests.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
      return <><div className="tv-discover-note"><Sparkles size={19}/><p>Good introductions start with something real. <strong>Yours start with shared interests.</strong></p></div>{renderTopicFilters()}{people.length ? <div className="tv-people-grid">{people.map(p => { const shared = sharedInterests(me!, p); const connected = data.contacts.some(c => c.id === p.id); const requested = data.requests.some(r => r.person.id === p.id && r.state === 'pending'); return <article className="tv-card tv-person-card" key={p.id}><div className="tv-person-top"><Avatar person={p} size="lg"/><span className="tv-connection-hint">{shared.length ? <><Sparkles size={13}/>{shared.length} in common</> : <><MapPin size={13}/>Same campus</>}</span></div><h3>{p.name}</h3><span className="tv-person-intent">Here to {p.intent.toLowerCase()}</span><p>{p.bio || 'A new face on your campus. Start with a shared interest.'}</p><div className="tv-tags">{p.interests.slice(0, 4).map(t => <Tag key={t} tint={shared.includes(t) ? 'green' : ''}>{t}</Tag>)}</div><button className="tv-btn secondary full" onClick={() => setPerson(p)}>{connected ? 'You’re connected' : requested ? 'Connection pending' : `Meet ${p.name.split(' ')[0]}`}<ArrowUpRight size={17}/></button></article>; })}</div> : <Empty title={search || topic !== 'All' ? 'A little too specific?' : 'Be one of the first.'} text={search || topic !== 'All' ? 'Try another interest or clear your search.' : 'New discoverable members in your campus and age group will appear here. Start a circle to give them a place to belong.'} action={search || topic !== 'All' ? 'Clear filters' : 'Start a circle'} onAction={() => { if (search || topic !== 'All') { setSearch(''); setTopic('All'); } else setCompose('circle'); }}/>}</>;
    }
    if (actualView === 'circles') return <><div className="tv-section-toolbar">{renderTabs(['Explore circles', 'My circles'])}<button className="tv-btn primary small" onClick={() => setCompose('circle')}><Plus size={16}/>Start a circle</button></div>{renderTopicFilters()}<ActivityGrid items={data.items.filter(i => i.kind === 'circle' && filterItem(i) && (tab !== 'My circles' || i.joined))} emptyTitle="A shared interest needs a first hello." emptyText="Start a small circle around something you love. Or try another interest." create="circle"/></>;
    if (actualView === 'plans') return <><div className="tv-section-toolbar">{renderTabs(['Upcoming', 'My plans', 'Past'])}<button className="tv-btn primary small" onClick={() => setCompose('plan')}><Plus size={16}/>Make a plan</button></div>{renderTopicFilters()}<ActivityGrid items={data.items.filter(i => i.kind === 'plan' && filterItem(i) && (tab === 'Past' ? (i.startsAt ?? 0) <= now : (i.startsAt ?? 0) > now) && (tab !== 'My plans' || i.joined)).sort((a,b) => (a.startsAt ?? 0) - (b.startsAt ?? 0))} emptyTitle={tab === 'My plans' ? 'Something to look forward to.' : 'The best plans start small.'} emptyText="Find a public spot, a little time, and a shared interest. You can make the first move." create="plan"/></>;
    if (actualView === 'saved') return <>{renderTabs(['Everything', 'Moments', 'Circles', 'Plans'])}<ActivityGrid items={data.items.filter(i => i.saved && filterItem(i) && (!tab || tab === 'Everything' || i.kind === ({ Moments: 'post', Circles: 'circle', Plans: 'plan' } as Record<string,string>)[tab]))} emptyTitle="A little collection of good things." emptyText="Tap the bookmark on a post or activity to save it here."/></>;
    if (actualView === 'profile') return <><section className="tv-card tv-my-profile"><div className="tv-my-profile-cover"><span>MORE THAN A PROFILE.</span><Flower2 size={100} strokeWidth={0.8}/></div><div className="tv-my-profile-info"><Avatar person={me!} size="xl"/><button className="tv-btn secondary small" onClick={() => navigate('settings')}>Edit profile<ArrowUpRight size={16}/></button><h2>{me!.name}</h2><p className="tv-small"><MapPin size={15}/>{me!.hub}<span>·</span>{me!.intent}</p><p>{me!.bio || 'Add a little about yourself to make introductions easier.'}</p><div className="tv-tags">{me!.interests.map(t => <Tag key={t}>{t}</Tag>)}</div><div className="tv-profile-stats"><button onClick={() => setTab('Moments')}><b>{data.items.filter(i => i.mine && i.kind === 'post').length}</b><span>Moments</span></button><button onClick={() => setTab('Circles')}><b>{joined.length}</b><span>Circles</span></button><button onClick={() => setTab('Plans')}><b>{upcoming.filter(i => i.joined).length}</b><span>Upcoming plans</span></button></div></div></section>{renderTabs(['Moments', 'Circles', 'Plans'])}<ActivityGrid items={data.items.filter(i => filterItem(i) && (tab === 'Circles' ? i.kind === 'circle' && i.joined : tab === 'Plans' ? i.kind === 'plan' && i.joined : i.kind === 'post' && i.mine))} emptyTitle="Your story starts here." emptyText="Share a moment, join a circle, or make a plan. This space will grow with you." create={!tab || tab === 'Moments' ? 'post' : undefined}/></>;
    const posts = data.items.filter(i => i.kind === 'post' && filterItem(i) && (tab !== 'Photos' || !!i.cover));
    if (!tab || tab === 'For you') posts.sort((a, b) => Number(me!.interests.includes(b.topic)) - Number(me!.interests.includes(a.topic)) || b.createdAt - a.createdAt);
    const feature = upcoming.find(i => !i.joined) ?? upcoming[0];
    return <><section className="tv-feed-hero"><img src={feature ? coverSrc(feature.cover) || '/campus.jpg' : '/campus.jpg'} alt="A little inspiration to spend time together"/><div className="tv-hero-shade"/><div className="tv-hero-copy"><span className="tv-hero-kicker"><span/>{feature ? 'YOUR NEXT GOOD AFTERNOON' : 'REAL LIFE IS CALLING'}</span><h2>{feature ? <>Less scrolling.<br/><em>More this.</em></> : <>A small hello.<br/><em>A better day.</em></>}</h2><p>{feature ? feature.title : 'Turn something you love into something you do together.'}</p><button className="tv-btn light" onClick={() => feature ? setDetail(feature.id) : setCompose('plan')}>{feature ? 'Take a look' : 'Make the first plan'}<ArrowUpRight size={17}/></button></div>{feature && <span className="tv-hero-date"><CalendarDays size={14}/>{new Date(feature.startsAt!).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })}</span>}</section>
      <section className="tv-card tv-quick-compose"><div className="tv-row"><Avatar person={me!}/><button onClick={() => setCompose('post')}>Got a little something to share, {me!.name.split(' ')[0]}?<Plus size={19}/></button></div><div className="tv-compose-shortcuts"><button onClick={() => setCompose('post')}><ImagePlus size={17}/>A moment</button><button onClick={() => setCompose('circle')}><Users size={17}/>A circle</button><button onClick={() => setCompose('plan')}><CalendarDays size={17}/>A plan</button><span>Something good starts here.</span></div></section>
      <div className="tv-section-toolbar">{renderTabs(['For you', 'Latest', 'Photos'])}<span className="tv-feed-scope"><MapPin size={13}/>Your campus</span></div>{renderTopicFilters()}<div className="tv-feed-list">{posts.slice(0,12).map(item => <PostCard key={item.id} item={item} actions={actions}/>)}{!posts.length && <Empty icon={<Camera/>} title={search || topic !== 'All' ? 'No moments here just yet.' : 'Someone has to say the first hello.'} text={search || topic !== 'All' ? 'Try a different interest or share the first moment.' : 'A question, a photo, a small idea. Give your campus something to connect over.'} action="Share a moment" onAction={() => setCompose('post')}/>}</div><div className="tv-feed-end"><span className="tv-end-line"/><Leaf size={25}/><h3>{posts.length > 12 ? 'A few good moments are enough.' : 'You’re all caught up.'}</h3><p>That’s a little of what’s happening here.<br/>Now go make something happen out there.</p><button className="tv-text-btn" onClick={() => navigate('plans')}>Find a plan<ArrowUpRight size={16}/></button><span className="tv-end-line"/></div>
    </>;
  }
  return <ModalErrorContext.Provider value={error}><div className="tv-app"><a className="tv-skip" href="#main-content">Skip to content</a><aside className="tv-sidebar"><button className="tv-brand-button" onClick={() => navigate('feed')} aria-label="Toveli home"><Brand/></button><span className="tv-sidebar-eyebrow">A PLACE TO BELONG</span><nav aria-label="Main navigation">{navigation.map(n => <button key={n.view} className={actualView === n.view ? 'active' : ''} aria-current={actualView === n.view ? 'page' : undefined} onClick={() => navigate(n.view)}><n.icon size={21} strokeWidth={1.7}/><span>{n.label}</span>{n.view === 'chat' && pending > 0 && <b className="tv-nav-count">{pending}</b>}{actualView === n.view && <span className="tv-nav-dot"/>}</button>)}<div className="tv-nav-divider"/><button className={actualView === 'saved' ? 'active' : ''} onClick={() => navigate('saved')}><Bookmark size={21} strokeWidth={1.7}/><span>Saved for later</span></button><button className={actualView === 'profile' ? 'active' : ''} onClick={() => navigate('profile')}><Heart size={21} strokeWidth={1.7}/><span>Your space</span></button></nav>
      <div className="tv-sidebar-circles"><div className="tv-row between"><span className="tv-sidebar-eyebrow">YOUR CIRCLES</span><button className="tv-icon-btn" onClick={() => me ? setCompose('circle') : navigate('onboard')} aria-label="Create a circle"><Plus size={15}/></button></div>{joined.slice(0, 3).map(i => <button key={i.id} onClick={() => setDetail(i.id)}><img src={coverSrc(i.cover) || '/scenes/desk.jpg'} alt=""/><span>{i.title}</span></button>)}{!joined.length && <p>Shared interests feel better<br/>with a little company.</p>}<button className="tv-find-circle" onClick={() => navigate('circles')}><Plus size={16}/>Find your circle</button></div>
      <div className="tv-sidebar-bottom"><div className="tv-offline-note"><Leaf size={17}/><span>A little online.<br/><strong>A lot more out there.</strong></span></div><button className="tv-sidebar-profile" aria-label="Your profile and preferences" onClick={() => navigate('settings')}>{me ? <Avatar person={me} size="sm"/> : <span className="tv-avatar sm">T</span>}<span><strong>{me?.name || 'Your space'}</strong><small>{demo ? 'Exploring the demo' : 'Profile & preferences'}</small></span><Settings2 size={17}/></button></div>
    </aside><div className="tv-main-wrap"><header className="tv-topbar"><button className="tv-mobile-brand" onClick={() => navigate('feed')} aria-label="Toveli home"><Brand compact/></button><button className="tv-campus-switch" onClick={() => navigate(me ? 'settings' : 'onboard')}><span className="tv-campus-icon"><MapPin size={17}/></span><span><small>YOUR LITTLE WORLD</small><strong>{me?.hub || 'Choose your campus'}</strong></span><ChevronDown size={15}/></button><div className="tv-global-search"><Search size={17}/><input aria-label="Search current view" disabled={!me || actualView === 'settings' || actualView === 'onboard'} placeholder={actualView === 'chat' ? 'Find a conversation…' : 'Search your campus…'} value={search} onChange={e => setSearch(e.target.value)}/>{search && <button aria-label="Clear search" onClick={() => setSearch('')}><X size={15}/></button>}</div><button className={`tv-icon-btn tv-bell ${actualView === 'notifications' ? 'active' : ''}`} onClick={() => navigate('notifications')} aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`}><Bell size={20}/>{unread > 0 && <span/>}</button><button className="tv-btn primary tv-top-create" onClick={() => me ? setCompose('post') : navigate('onboard')}><Plus size={17}/>Create</button><button className="tv-mobile-more tv-icon-btn" aria-label="Open your menu" aria-expanded={moreOpen} onClick={() => setMoreOpen(!moreOpen)}>{me ? <Avatar person={me} size="sm"/> : <Settings2/>}</button></header>
      {demo && <div className="tv-demo-banner"><span><Sparkles size={14}/><strong>Interactive demo</strong><span>Sample people & activity. Your changes stay in this browser.</span></span><Link href="/login">Make it yours<ArrowUpRight size={14}/></Link></div>}
      {moreOpen && <div className="tv-mobile-menu">{(['profile','saved','settings'] as View[]).map(v => <button key={v} onClick={() => navigate(v)}>{v === 'profile' ? 'Your space' : v === 'saved' ? 'Saved for later' : 'Preferences'}<ArrowUpRight size={17}/></button>)}</div>}
      <main className={`tv-main ${actualView === 'chat' ? 'tv-main-inbox' : ''}`} id="main-content"><div className="tv-page-heading"><div><span className="tv-eyebrow">{headings[actualView][0]}</span><h1>{headings[actualView][1]}</h1><p>{headings[actualView][2]}</p></div>{actualView === 'feed' && <span className="tv-heading-flower"><Flower2 size={47} strokeWidth={1.1}/></span>}</div>
        {error && <div className="tv-error" role="alert"><span>{error}</span><button onClick={() => { setError(''); void state.refresh(); }} aria-label="Retry loading"><RefreshCw size={17}/></button><button onClick={() => setError('')} aria-label="Dismiss error"><X size={17}/></button></div>}
        {loading ? <div className="tv-loading" role="status"><LoaderCircle size={25} className="tv-spin"/><p>Finding your little world…</p><div className="tv-skeleton"/><div className="tv-skeleton short"/></div> : !data ? <Empty title="Let’s try that again." text="We couldn’t reach your campus. Your previous activity is still safe." action="Retry" onAction={() => void state.refresh()}/> : <div className={['feed','radar','circles','plans','profile','saved'].includes(actualView) ? 'tv-columns' : ''}><div className="tv-content">{renderContent()}</div>{['feed','radar','circles','plans','profile','saved'].includes(actualView) && renderRail()}</div>}
      </main></div><nav className="tv-bottom-nav" aria-label="Mobile navigation">{navigation.map(n => <button key={n.view} aria-current={actualView === n.view ? 'page' : undefined} className={actualView === n.view ? 'active' : ''} onClick={() => navigate(n.view)}><n.icon size={21} strokeWidth={1.8}/><span>{n.view === 'radar' ? 'Discover' : n.view === 'feed' ? 'Home' : n.view === 'plans' ? 'Plans' : n.label}</span>{n.view === 'chat' && pending > 0 && <i/>}</button>)}</nav>
      {toast && <div className="tv-toast" role="status"><Check size={18}/>{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16}/></button></div>}
      {compose && me && <Composer initialKind={compose} busy={busy} mutate={mutate} onClose={() => setCompose(null)}/>}
      {currentItem && <ItemDetail item={currentItem} actions={actions} onClose={() => setDetail(null)}/>}
      {currentPerson && data && <PersonDetail person={currentPerson} data={data} busy={busy} mutate={mutate} onClose={() => setPerson(null)} message={id => navigate('chat', id)} block={p => { setPerson(null); setManage({ person: p, action: 'block' }); }}/>}
      {manage && <Modal title={manage.action === 'report' ? 'Tell us what’s wrong.' : manage.action === 'block' ? `Block ${manage.person?.name}?` : manage.item?.kind === 'plan' ? 'Cancel this plan?' : 'Remove this from your campus?'} onClose={() => setManage(null)}><form className="tv-form" onSubmit={async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault(); const values = new FormData(e.currentTarget);
        const action = manage.action === 'block' ? { kind: 'block', personId: manage.person!.id } : manage.action === 'report' ? { kind: 'report', id: manage.item!.id, reason: String(values.get('reason')) } : { kind: 'delete', id: manage.item!.id };
        if (await mutate(action, manage.action === 'report' ? demo ? 'Demo only. No moderation report was submitted.' : 'Report received for review.' : manage.action === 'block' ? 'Member blocked. Your connection has been removed.' : 'Removed from your campus.')) setManage(null);
      }}><p className="tv-muted">{manage.action === 'block' ? 'You won’t see each other’s profiles, posts, or messages here. This also cancels your connection.' : manage.action === 'report' ? 'Describe the issue. The report is private and goes to the moderation queue.' : 'This removes the item and its conversation for everyone. This can’t be undone.'}</p>{manage.action === 'report' && <label>What happened?<textarea name="reason" rows={4} minLength={3} maxLength={500} required placeholder="Tell us what needs attention…"/></label>}<div className="tv-form-footer"><button type="button" className="tv-btn secondary" onClick={() => setManage(null)}>Keep browsing</button><button className={`tv-btn ${manage.action === 'report' ? 'primary' : 'danger'}`} disabled={busy}>{busy ? 'Working…' : manage.action === 'report' ? 'Send report' : manage.action === 'block' ? 'Block member' : 'Remove'}</button></div></form></Modal>}
      {confirmLogout && <Modal title="See you out there." onClose={() => setConfirmLogout(false)}><p className="tv-muted">Sign out of this browser? Your profile and activity will be here when you return.</p><div className="tv-form-footer"><button className="tv-btn secondary" onClick={() => setConfirmLogout(false)}>Stay here</button><button className="tv-btn primary" onClick={async () => { try { const r = await fetch('/api/auth/logout', { method: 'POST' }); if (!r.ok) throw new Error('Could not sign out. Try again.'); location.href = '/'; } catch (e) { setError((e as Error).message); setConfirmLogout(false); } }}>Sign out<LogOut size={16}/></button></div></Modal>}
    </div></ModalErrorContext.Provider>;
}
